<?php
session_start();
require_once '../includes/db.php';
require_once '../includes/assessment.php';
$context = assessment_teacher_context($conn);
$report = assessment_report_data($conn, $context);
$students = $report['students'];
$preScores = []; $postScores = []; $gameScores = [];
$lessonStats = array_fill(1, 4, ['pre'=>[], 'post'=>[]]);
foreach ($students as $student) {
    if ($student['pre']) $preScores[] = intval($student['pre']['score']);
    if ($student['post']) $postScores[] = intval($student['post']['score']);
    $gameScores[] = intval($student['game_score']);
    foreach ($student['lessons'] as $lesson => $scores) {
        if ($student['pre']) $lessonStats[$lesson]['pre'][] = $scores['pre'];
        if ($student['post']) $lessonStats[$lesson]['post'][] = $scores['post'];
    }
}
$preMean=assessment_mean($preScores);$postMean=assessment_mean($postScores);$e1=assessment_mean($gameScores)/36*100;$e2=$postMean/20*100;
$lessonNames=[1=>'การใช้เหตุผลเชิงตรรกะ',2=>'การเรียงลำดับขั้นตอน',3=>'การใช้เงื่อนไข',4=>'การตรวจสอบและแก้ไขข้อผิดพลาด'];
?>
<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ผลสอบก่อน–หลังเรียน</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;600&display=swap" rel="stylesheet"><style>body{font-family:Kanit,sans-serif;background:#f1f5f9}.card{border:0;border-radius:18px}.metric{font-size:2rem;font-weight:700}.bar{height:10px;border-radius:8px;background:#e2e8f0;overflow:hidden}.bar>span{display:block;height:100%;background:#10b981}</style></head><body>
<nav class="navbar navbar-dark bg-primary"><div class="container"><span class="navbar-brand fw-bold"><i class="bi bi-bar-chart-fill"></i> ผลสอบก่อน–หลังเรียน</span><div class="d-flex gap-2"><a class="btn btn-success btn-sm rounded-pill" href="../api/export_assessment_scores.php?classroom_id=<?php echo $context['classroom_id'];?>"><i class="bi bi-download"></i> Export CSV</a><a class="btn btn-light btn-sm rounded-pill" href="dashboard.php?classroom_id=<?php echo $context['classroom_id'];?>">กลับ Dashboard</a></div></div></nav>
<main class="container py-4"><div class="mb-3"><h3 class="fw-bold mb-1"><?php echo htmlspecialchars($context['classroom']['classroom_name']);?></h3><div class="text-muted"><?php echo htmlspecialchars($context['learning_session']['session_name']);?></div></div>
<?php if(isset($_GET['reset'])):?><div class="alert alert-<?php echo $_GET['reset']==='1'?'success':'warning';?>"><?php echo $_GET['reset']==='1'?'Reset การสอบแล้ว':'ไม่พบรายการที่ Reset ได้';?></div><?php endif;?>
<?php if(!$report['settings']):?><div class="alert alert-warning">ยังไม่ได้ตั้งค่าชุดข้อสอบสำหรับรอบนี้ <a href="assessment_settings.php">ไปหน้าตั้งค่า</a></div><?php endif;?>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted">เฉลี่ยก่อนเรียน</div><div class="metric text-success"><?php echo number_format($preMean,2);?>/20</div><small>SD <?php echo number_format(assessment_standard_deviation($preScores),2);?></small></div></div></div><div class="col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted">เฉลี่ยหลังเรียน</div><div class="metric text-primary"><?php echo number_format($postMean,2);?>/20</div><small>SD <?php echo number_format(assessment_standard_deviation($postScores),2);?></small></div></div></div><div class="col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted">ประสิทธิภาพ E1</div><div class="metric text-warning"><?php echo number_format($e1,2);?>%</div><small>คะแนนเกมเฉลี่ย / 36</small></div></div></div><div class="col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted">ประสิทธิภาพ E2</div><div class="metric text-danger"><?php echo number_format($e2,2);?>%</div><small>Post-test เฉลี่ย / 20</small></div></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-body"><h5 class="fw-bold mb-3">กราฟเปรียบเทียบคะแนนเฉลี่ยก่อน–หลังเรียน</h5><div class="row g-3 align-items-center"><div class="col-md-2 fw-bold text-success">Pre-test</div><div class="col-md-8"><div class="bar" style="height:22px"><span style="width:<?php echo min(100,$preMean/20*100);?>%;background:#10b981"></span></div></div><div class="col-md-2 text-md-end"><?php echo number_format($preMean,2);?>/20</div><div class="col-md-2 fw-bold text-primary">Post-test</div><div class="col-md-8"><div class="bar" style="height:22px"><span style="width:<?php echo min(100,$postMean/20*100);?>%;background:#2563eb"></span></div></div><div class="col-md-2 text-md-end"><?php echo number_format($postMean,2);?>/20</div></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-header bg-white fw-bold py-3">รายงานรายบุคคล</div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>นักเรียน</th><th>Pre-test</th><th>Post-test</th><th>ผลต่าง</th><th>ร้อยละพัฒนา</th><th>คะแนนเกม</th><th>สถานะ</th><th></th></tr></thead><tbody><?php foreach($students as $student):$pre=$student['pre']?intval($student['pre']['score']):null;$post=$student['post']?intval($student['post']['score']):null;$diff=($pre!==null&&$post!==null)?$post-$pre:null;?><tr><td><strong><?php echo htmlspecialchars($student['name']);?></strong><br><small class="text-muted"><?php echo htmlspecialchars($student['student_id']);?></small></td><td><?php echo $pre===null?'-':$pre.'/20';?></td><td><?php echo $post===null?'-':$post.'/20';?></td><td class="fw-bold <?php echo $diff!==null&&$diff>=0?'text-success':'text-danger';?>"><?php echo $diff===null?'-':sprintf('%+d',$diff);?></td><td><?php echo $diff===null?'-':number_format($diff/20*100,2).'%';?></td><td><?php echo intval($student['game_score']);?>/36</td><td><span class="badge bg-<?php echo $pre!==null&&$post!==null?'success':'secondary';?>"><?php echo $pre!==null&&$post!==null?'ครบ':'ยังไม่ครบ';?></span></td><td><?php foreach(['pre','post'] as $key):if($student[$key]):?><form method="post" action="../api/reset_assessment_attempt.php" class="d-inline" onsubmit="return confirm('ยืนยัน Reset ผลสอบรายการนี้?')"><input type="hidden" name="csrf_token" value="<?php echo assessment_csrf_token();?>"><input type="hidden" name="classroom_id" value="<?php echo $context['classroom_id'];?>"><input type="hidden" name="attempt_id" value="<?php echo $student[$key]['id'];?>"><button class="btn btn-outline-danger btn-sm">Reset <?php echo $key==='pre'?'Pre':'Post';?></button></form><?php endif;endforeach;?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card shadow-sm"><div class="card-header bg-white fw-bold py-3">วิเคราะห์รายบทเรียน</div><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>บทเรียน</th><th>Pre-test เฉลี่ย</th><th>Post-test เฉลี่ย</th><th>ผลต่าง</th><th style="min-width:180px">ภาพรวมหลังเรียน</th></tr></thead><tbody><?php foreach($lessonNames as $id=>$name):$lp=assessment_mean($lessonStats[$id]['pre']);$lpost=assessment_mean($lessonStats[$id]['post']);?><tr><td><strong>บท <?php echo $id;?></strong> <?php echo $name;?></td><td><?php echo number_format($lp,2);?>/5</td><td><?php echo number_format($lpost,2);?>/5</td><td class="text-success">+<?php echo number_format($lpost-$lp,2);?></td><td><div class="bar"><span style="width:<?php echo min(100,$lpost/5*100);?>%"></span></div><small><?php echo $lpost>=4?'พัฒนาดี':($lpost>=3?'อยู่ในระดับน่าพอใจ':'ควรเสริมทักษะ');?></small></td></tr><?php endforeach;?></tbody></table></div></div></div></main></body></html>
