<?php
session_start();
require_once '../includes/db.php';
require_once '../includes/survey.php';
$app = require __DIR__ . '/../config/app.php';
$context = survey_teacher_context($conn);
$report = survey_report_data($conn, $context);
$summary = $report['summary'];
?>
<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ผลความพึงพอใจ | <?php echo htmlspecialchars($app['app_name']); ?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;600;700&display=swap" rel="stylesheet"><style>body{font-family:Kanit,sans-serif;background:#f8fafc}.stat-card,.report-card{border:0;border-radius:1.25rem;box-shadow:0 10px 28px rgba(15,23,42,.07)}@media print{nav,.no-print{display:none!important}body{background:#fff}.report-card,.stat-card{box-shadow:none;border:1px solid #ddd}}</style></head>
<body><nav class="navbar navbar-dark bg-success"><div class="container"><span class="navbar-brand fw-bold"><i class="bi bi-bar-chart-fill"></i> ผลความพึงพอใจ</span><div class="d-flex gap-2"><a class="btn btn-light btn-sm rounded-pill" href="survey_responses.php?classroom_id=<?php echo $context['classroom_id']; ?>">สถานะรายคน</a><a class="btn btn-warning btn-sm rounded-pill" href="export_survey_results.php?classroom_id=<?php echo $context['classroom_id']; ?>">Export</a><a class="btn btn-outline-light btn-sm rounded-pill" href="dashboard.php?classroom_id=<?php echo $context['classroom_id']; ?>">Dashboard</a></div></div></nav>
<main class="container py-4"><div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h2 class="fw-bold mb-1"><?php echo htmlspecialchars($report['settings']['title'] ?? 'แบบสอบถามความพึงพอใจ'); ?></h2><div class="text-muted"><?php echo htmlspecialchars($context['classroom']['classroom_name']); ?> | <?php echo htmlspecialchars($context['learning_session']['session_name'] ?? 'รอบการเรียนรู้หลัก'); ?></div></div><button onclick="print()" class="btn btn-outline-secondary rounded-pill no-print"><i class="bi bi-printer"></i> พิมพ์รายงาน</button></div>
<?php if (empty($report['settings']['survey_id'])): ?><div class="alert alert-warning">ยังไม่ได้กำหนดแบบสอบถามสำหรับรอบการเรียนรู้นี้ <a href="survey_settings.php?classroom_id=<?php echo $context['classroom_id']; ?>">ไปตั้งค่า</a></div><?php endif; ?>
<div class="row g-3 mb-4"><?php foreach([['นักเรียนทั้งหมด',$summary['total_students'],'bi-people','primary'],['ตอบแล้ว',$summary['responded'],'bi-check2-circle','success'],['ร้อยละผู้ตอบ',number_format($summary['response_percent'],2).'%','bi-pie-chart','info'],['ค่าเฉลี่ยรวม',number_format($summary['mean'],2),'bi-star-fill','warning'],['S.D.',number_format($summary['sd'],2),'bi-activity','secondary'],['ระดับ',$summary['level'],'bi-award','success']] as $stat): ?><div class="col-6 col-lg-2"><div class="card stat-card h-100"><div class="card-body text-center"><i class="bi <?php echo $stat[2]; ?> text-<?php echo $stat[3]; ?> fs-3"></i><div class="small text-muted mt-1"><?php echo $stat[0]; ?></div><div class="fw-bold fs-4"><?php echo $stat[1]; ?></div></div></div></div><?php endforeach; ?></div>

<section class="card report-card mb-4"><div class="card-body p-0"><div class="p-4 pb-2"><h4 class="fw-bold">ผลรายด้าน</h4></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-success"><tr><th class="ps-4">ด้าน</th><th class="text-center">ผู้ตอบ</th><th class="text-center">ค่าเฉลี่ย</th><th class="text-center">S.D.</th><th class="text-center pe-4">ระดับ</th></tr></thead><tbody><?php foreach($report['category_stats'] as $category): ?><tr><td class="ps-4 fw-semibold"><?php echo htmlspecialchars($category['name']); ?></td><td class="text-center"><?php echo $category['respondents']; ?></td><td class="text-center fw-bold"><?php echo number_format($category['mean'],2); ?></td><td class="text-center"><?php echo number_format($category['sd'],2); ?></td><td class="text-center pe-4"><span class="badge bg-success bg-opacity-10 text-success"><?php echo $category['level']; ?></span></td></tr><?php endforeach; ?><tr class="table-light fw-bold"><td class="ps-4">รวม</td><td class="text-center"><?php echo $summary['responded']; ?></td><td class="text-center"><?php echo number_format($summary['mean'],2); ?></td><td class="text-center"><?php echo number_format($summary['sd'],2); ?></td><td class="text-center pe-4"><?php echo $summary['level']; ?></td></tr></tbody></table></div></div></section>

<section class="card report-card mb-4"><div class="card-body p-0"><div class="p-4 pb-2"><h4 class="fw-bold">ผลรายข้อ</h4></div><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">ข้อ</th><th>ข้อความ</th><th class="text-center">เฉลี่ย</th><th class="text-center">S.D.</th><th class="text-center pe-4">ระดับ</th></tr></thead><tbody><?php foreach($report['item_stats'] as $item): ?><tr><td class="ps-4 fw-bold"><?php echo intval($item['question']['question_no']); ?></td><td><?php echo htmlspecialchars($item['question']['question_text']); ?><br><small class="text-muted"><?php echo htmlspecialchars($item['question']['category_name']); ?></small></td><td class="text-center fw-bold"><?php echo number_format($item['mean'],2); ?></td><td class="text-center"><?php echo number_format($item['sd'],2); ?></td><td class="text-center pe-4"><?php echo $item['level']; ?></td></tr><?php endforeach; ?></tbody></table></div></div></section>

<section class="card report-card"><div class="card-body p-4"><h4 class="fw-bold">ความคิดเห็นปลายเปิด</h4><?php if(!$report['comments']): ?><div class="text-muted">ยังไม่มีความคิดเห็นปลายเปิด</div><?php else: ?><div class="row g-3"><?php foreach($report['comments'] as $comment): ?><div class="col-md-6"><div class="border rounded-4 p-3 h-100"><div class="fw-bold text-success"><?php echo htmlspecialchars($comment['student_id'].' '.$comment['name']); ?></div><?php foreach($report['open_questions'] as $question): $answer=$comment['answers'][intval($question['id'])]??''; if($answer==='')continue; ?><div class="mt-2"><small class="text-muted"><?php echo htmlspecialchars($question['question_text']); ?></small><div><?php echo nl2br(htmlspecialchars($answer)); ?></div></div><?php endforeach; ?></div></div><?php endforeach; ?></div><?php endif; ?></div></section>
</main></body></html>
